version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: project_postgres_prod
    restart: always
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  backend:
    build:
      context: ./nodejs
    container_name: project_backend_prod
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env.production
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: .
    container_name: project_frontend_prod
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backup:
    image: postgres:15
    container_name: project_backup_prod
    depends_on:
      - postgres
    env_file:
      - .env.production
    volumes:
      - ./nodejs/database/backups:/backups
    entrypoint: >
      bash -c "
      while true; do
        pg_dump -h postgres -U ${DB_USER} ${DB_NAME} > /backups/backup_$(date +%Y-%m-%d_%H-%M-%S).sql;
        sleep 86400;
      done
      "
volumes:
  postgres_data_prod: