version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: project_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: project_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./nodejs:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: